[build]
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' cdnjs.cloudflare.com; font-src 'self' cdnjs.cloudflare.com" 